### PR TITLE
Arcgis - default geospatial database location to Speckle folder

### PR DESCRIPTION
**Pull request by KatKatKateryna**
If Project location is not writeable, save the .gdb file to the Speckle folder

### CODE REVIEW

**Comment by KatKatKateryna** [comment]
@AlanRynne here is the PR for defaulting it to Temp folder, once Speckle path is public I will replace

**Comment by KatKatKateryna** [comment]
not sure if failing test is related to updated nugets

**Comment by AlanRynne** [comment]
Missing the lock file changes after changing a nuget version.

`dotnet restore` and commit the lock files should do it.

**Comment by KatKatKateryna** [comment]
moving here: https://github.com/specklesystems/speckle-sharp-connectors/pull/351 @AlanRynne

**Pull request closed without merging**
