### PR TITLE
Switch tracing to seq dev.  Turn off tracing to console when debugging

### PR DESCRIPTION
**Pull request by adamhathcock**

### CODE REVIEW

**Review by AlanRynne — CHANGES_REQUESTED** [review]
I think this should go into `main` right? Otherwise everything is good

**Comment by adamhathcock** [comment]
I guess it should go to both.  I'll put it on main so we can put it in dev

**Comment by adamhathcock** [comment]
Actually, this class is newer than the current main :)

Main is like 2 months old, that doesn't seem right 🤔

**Review by AlanRynne — APPROVED** [review]
Oh yeah, we still need to do the merge to main. Approving into dev for now, it'll make it's way there

**Pull request merged**
